---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: install
  description: This role installs and does initial configuration for PostgreSQL on Linux systems.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - '9'
        - '8'
    - name: Ubuntu
      versions:
        - noble
        - jammy

collections:
  - ansible.posix
  - community.general
  - community.hashi_vault
  - community.postgresql
  - trippsc2.hashi_vault

dependencies: []
